import { BridgeEvents } from './bridge'
import { Events } from './events'

export const ForwardableEvents = [
  Events.TaskUpdated,
  Events.TaskFilesUpdated,
  Events.TaskActivityUpdated,
  Events.TaskInspectorActivityUpdated,
  Events.MagnetFileSelection,
  Events.StatsUpdated,
  Events.EngineDisconnected,
  Events.EngineRecovered,
  Events.EngineReconnecting,
  Events.EngineStateChanged,
  Events.EngineActiveChanged,
  Events.EngineRestartRequired,
  Events.PortConflict,
  Events.PluginError,
  Events.PluginTimeout,
  Events.PluginStatusChanged,
  Events.PluginInstalled,
  Events.PluginUninstalled,
  Events.NatStateChanged,
  Events.NatMappingUpdated,
  Events.NatDiagnosticCompleted,
  Events.NatGatewayChanged,
  Events.NatError,
  Events.TuningUpdated,
  Events.TrackerListUpdated,
  Events.TrackerSyncFailed,
  Events.UpdateStateChanged,
  Events.UpdateCheckStarted,
  Events.UpdateAvailable,
  Events.UpdateNotAvailable,
  Events.UpdateDownloadProgress,
  Events.UpdateDownloaded,
  Events.UpdateCancelled,
  Events.UpdateError,
  Events.GeoIPUpdateProgress,
  Events.GeoIPStatusChanged,
  Events.LocaleChanged,
  Events.PluginConfigChanged,
  Events.PluginGrantsChanged,
  Events.PluginEvicted,
  Events.PluginActivationCapExceeded,
  Events.SpeedLimitChanged,
  Events.NotificationAdded,
  Events.NotificationsChanged,
  // Bridge approval events (Spec 7b) — forwarded so the web renderer's pairing
  // toast + paired-client list work on the server shell, same as Electron IPC.
  BridgeEvents.PairRequested,
  BridgeEvents.Paired,
  BridgeEvents.Revoked,
  BridgeEvents.Error,
  // Pending pair request lifecycle (pending -> settled | expired) — same
  // web-shell forwarding rationale as the approval events above.
  BridgeEvents.PairRequestSettled,
  BridgeEvents.PairRequestExpired,
] as const
