export const MenuIds = {
  MenubarApp: 'menubar.app',
  MenubarFile: 'menubar.file',
  MenubarTask: 'menubar.task',
  MenubarEdit: 'menubar.edit',
  MenubarWindow: 'menubar.window',
  MenubarHelp: 'menubar.help',
  Tray: 'tray.main',
} as const

export type MenuId = (typeof MenuIds)[keyof typeof MenuIds]

export const MenuItemIds = {
  AppAbout: 'menubar.app.about',
  AppPreferences: 'menubar.app.preferences',
  AppCheckForUpdates: 'menubar.app.checkForUpdates',
  AppShow: 'menubar.app.show',
  AppHide: 'menubar.app.hide',
  AppHideOthers: 'menubar.app.hideOthers',
  AppUnhide: 'menubar.app.unhide',
  AppQuit: 'menubar.app.quit',
  TaskNew: 'menubar.task.new',
  TaskNewBt: 'menubar.task.newBt',
  TaskOpenFile: 'menubar.task.openFile',
  TaskList: 'menubar.task.list',
  TaskPause: 'menubar.task.pause',
  TaskResume: 'menubar.task.resume',
  TaskDelete: 'menubar.task.delete',
  TaskMoveUp: 'menubar.task.moveUp',
  TaskMoveDown: 'menubar.task.moveDown',
  TaskPauseAll: 'menubar.task.pauseAll',
  TaskResumeAll: 'menubar.task.resumeAll',
  TaskSelectAll: 'menubar.task.selectAll',
  TaskClearStopped: 'menubar.task.clearStopped',
  EditUndo: 'menubar.edit.undo',
  EditRedo: 'menubar.edit.redo',
  EditCut: 'menubar.edit.cut',
  EditCopy: 'menubar.edit.copy',
  EditPaste: 'menubar.edit.paste',
  EditDelete: 'menubar.edit.delete',
  EditSelectAll: 'menubar.edit.selectAll',
  WindowReload: 'menubar.window.reload',
  WindowClose: 'menubar.window.close',
  WindowMinimize: 'menubar.window.minimize',
  WindowZoom: 'menubar.window.zoom',
  WindowToggleFullscreen: 'menubar.window.toggleFullscreen',
  WindowFront: 'menubar.window.front',
  HelpWebsite: 'menubar.help.website',
  HelpManual: 'menubar.help.manual',
  HelpChangelog: 'menubar.help.changelog',
  HelpReportProblem: 'menubar.help.reportProblem',
  HelpToggleDevTools: 'menubar.help.toggleDevTools',
  TrayNew: 'tray.new',
  TrayNewBt: 'tray.newBt',
  TrayOpenFile: 'tray.openFile',
  TrayShow: 'tray.show',
  TrayManual: 'tray.manual',
  TrayCheckForUpdates: 'tray.checkForUpdates',
  TrayPreferences: 'tray.preferences',
  TrayQuit: 'tray.quit',
  ApplicationSubmenusSeparator: 'application-menu.separator.submenus',
  ApplicationQuitSeparator: 'application-menu.separator.quit',
} as const
